version: "3"

services:
  jenkins:
    container_name: my_custom_jenkins
    image: jenkins/jenkins:alpine
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Named  Docker volume details at the bottom
      - jenkins_home:/var/jenkins_home
    networks:
      - net_devops

  sonarqube:
    container_name: my_custom_sonarqube
    # build: ./sonarqube_home
    image: sonarqube:lts
    ports:
      - "9000:9000"
    networks:
      - net_devops
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: unless-stopped
# To use docker-volume (custom_jenkins_home) instead of a directory path-file
volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:

networks:
  net_devops:
